### PR TITLE
bug: ts-node is a required dependency of server

### PR DESCRIPTION
**Pull request by jdjkelly**
### Why
* Docker Compose build was failing to actually launch the server process without ts-node installed

### CODE REVIEW

**Review by amcgivern — COMMENTED** [review]
It might be an issue with my configuration but the link/exchange step doesn't return a response after going through the Link flow:
Screen Shot 2022-10-17 at 4 45 37 PM

Here's the server log as well:
Screen Shot 2022-10-17 at 4 48 02 PM

**Comment by jdjkelly** [comment]
Did you add the required env values in compose.yaml?

```
Use Docker Compose with this project by, first, editing `compose.yaml` to add your Flexpa publishable and secret keys adding them to:

```bash
VITE_FLEXPA_PUBLISHABLE_KEY=
FLEXPA_API_SECRET_KEY=
```
```

**Comment by amcgivern** [comment]
Yep, I just double-checked their values but I'm still having the same issue.

**Comment by amcgivern** [comment]
My other thought is that it has something to do with my Docker version?
Here's the output of `docker version`

```bash
Client:
 Cloud integration: v1.0.29
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:04:45 2022
 OS/Arch:           darwin/arm64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.12.0 (85629)
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.11
  Git commit:       a89b842
  Built:            Mon Jun  6 23:01:01 2022
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.8
  GitCommit:        9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by jdjkelly** [comment]
I'm still not getting this - heres my end to end test: Screen Shot 2022-10-18 at 5 23 00 PM

**Comment by jdjkelly** [comment]
> My other thought is that it has something to do with my Docker version? Here's the output of `docker version`
> 
> ```shell
> Client:
>  Cloud integration: v1.0.29
>  Version:           20.10.17
>  API version:       1.41
>  Go version:        go1.17.11
>  Git commit:        100c701
>  Built:             Mon Jun  6 23:04:45 2022
>  OS/Arch:           darwin/arm64
>  Context:           default
>  Experimental:      true
> 
> Server: Docker Desktop 4.12.0 (85629)
>  Engine:
>   Version:          20.10.17
>   API version:      1.41 (minimum version 1.12)
>   Go version:       go1.17.11
>   Git commit:       a89b842
>   Built:            Mon Jun  6 23:01:01 2022
>   OS/Arch:          linux/arm64
>   Experimental:     false
>  containerd:
>   Version:          1.6.8
>   GitCommit:        9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
>  runc:
>   Version:          1.1.4
>   GitCommit:        v1.1.4-0-g5fd4c4d
>  docker-init:
>   Version:          0.19.0
>   GitCommit:        de40ad0
> ```
> 
> I haven't used Docker before so I'm sure what to look for in terms of configuration errors

I'm using the same...

```
λ › docker version                                ~
Client:
 Cloud integration: v1.0.29
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:04:45 2022
 OS/Arch:           darwin/arm64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.12.0 (85629)
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.11
  Git commit:       a89b842
  Built:            Mon Jun  6 23:01:01 2022
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.8
  GitCommit:        9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
  ````

**Comment by acr13** [comment]
I get the same as @amcgivern 

Looks like a cors error going from client -> server  I _think_ 🤔  

Screenshots of both requests

Screen Shot 2022-10-18 at 5 38 32 PM
Screen Shot 2022-10-18 at 5 38 38 PM

**Review by acr13 — APPROVED** [review]

**Pull request merged**
